# Generated by Django 2.1 on 2018-08-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubike', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubike_data',
            old_name='index',
            new_name='seq',
        ),
    ]
