# Generated by Django 2.1 on 2018-08-25 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubike', '0002_auto_20180824_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubike_data',
            name='sno',
            field=models.ForeignKey(db_column='sno', on_delete=django.db.models.deletion.CASCADE, related_name='snos_set', to='ubike.Ubike_info'),
        ),
    ]
