# Generated by Django 2.1 on 2018-08-25 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubike', '0003_auto_20180826_0535'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ubike_data',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ubike_info',
            table=None,
        ),
    ]
