# Generated by Django 2.1 on 2018-08-26 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubike', '0009_auto_20180826_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubike_data',
            name='sno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubike.Ubike_Info'),
        ),
    ]
