# Generated by Django 2.1 on 2018-08-26 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubike', '0011_auto_20180826_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubike_data',
            name='sno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snos', related_query_name='snos_query', to='ubike.Ubike_Info'),
        ),
    ]
